In [21]:
# First ANN model static architecture
import torch
import torch.nn as nn

class ANN(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(3,2)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(2,5)
        self.fc3 = nn.Linear(5,1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)

        x = self.fc2(x)
        x = self.relu(x)

        x = self.fc3(x)

        return x
model = ANN()
print(model)
f1 = float(input("Enter Feature 1: "))
f2 = float(input("Enter Feature 2: "))
f3 = float(input("Enter Feature 3: "))
x= torch.tensor([[f1,f2,f3]])
output=model(x)
print(output)



ANN(
  (fc1): Linear(in_features=3, out_features=2, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=2, out_features=5, bias=True)
  (fc3): Linear(in_features=5, out_features=1, bias=True)
)


Enter Feature 1:  34.5
Enter Feature 2:  56.7
Enter Feature 3:  68.9


tensor([[-0.4611]], grad_fn=<AddmmBackward0>)


In [22]:
# first ANN Model with dynamic architecture
import torch
import torch.nn as nn

class ANN(nn.Module):

    def __init__(self, in_features, hidden1, hidden2, hidden3, out_features):
        super().__init__()

        self.fc1 = nn.Linear(in_features, hidden1)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden1, hidden2)
        self.fc3 = nn.Linear(hidden2, hidden3)
        self.fc4 = nn.Linear(hidden3, out_features)

    def forward(self, x):

        x = self.fc1(x)
        x = self.relu(x)

        x = self.fc2(x)
        x = self.relu(x)

        x = self.fc3(x)
        x = self.relu(x)

        x = self.fc4(x)

        return x

model1 = ANN(
    in_features=3,
    hidden1=2,
    hidden2=5,
    hidden3=3,
    out_features=1)

model2 = ANN(
    in_features=4,
    hidden1=10,
    hidden2=8,
    hidden3=4,
    out_features=2)
f1 = float(input("Enter Feature 1: "))
f2 = float(input("Enter Feature 2: "))
f3 = float(input("Enter Feature 3: "))
f4 = float(input("Enter Feature 4: "))

x1 = torch.tensor([[f1,f2,f3]], dtype=torch.float32)
x2 = torch.tensor([[f1,f2,f3,f4]], dtype=torch.float32)
output1 = model1(x1)
output2 = model2(x2)
print(output1)
print(output2)

Enter Feature 1:  34.6
Enter Feature 2:  45.7
Enter Feature 3:  38.0
Enter Feature 4:  100.7


tensor([[0.4932]], grad_fn=<AddmmBackward0>)
tensor([[-0.3848,  1.7175]], grad_fn=<AddmmBackward0>)
