In [6]:
# forward pass
# normal input static
import torch
import torch.nn as nn

#creating layers
fc1 = nn.Linear(2,3)
relu= nn.ReLU()
fc2=nn.Linear(3,1)
x=torch.tensor([[10.0,20.0]])
x=fc1(x)
print("after fc1")
print(x)
x=relu(x)
print("after relu")
print(x)
x=fc2(x)
print("final prediction")
print(x)

after fc1
tensor([[-0.0382, -3.5158, -7.4472]], grad_fn=<AddmmBackward0>)
after relu
tensor([[0., 0., 0.]], grad_fn=<ReluBackward0>)
final prediction
tensor([[-0.4342]], grad_fn=<AddmmBackward0>)


In [16]:
# dynamic inputs/feature
import torch
import torch.nn as nn
fc1= nn.Linear(2,4)
relu=nn.ReLU()
fc2 = nn.Linear(4,1)
f1 = float(input("Enter Feature 1: "))
f2 = float(input("Enter Feature 2: "))

x= torch.Tensor([[f1,f2]])
x = fc1(x)
print("\nAfter fc1:")
print(x)

x = relu(x)
print("\nAfter ReLU:")
print(x)

x = fc2(x)
print("\nPrediction:")
print(x)


Enter Feature 1:  46.6
Enter Feature 2:  35.8



After fc1:
tensor([[ 23.6448,  35.5246, -16.6034,  13.2324]], grad_fn=<AddmmBackward0>)

After ReLU:
tensor([[23.6448, 35.5246,  0.0000, 13.2324]], grad_fn=<ReluBackward0>)

Prediction:
tensor([[8.5987]], grad_fn=<AddmmBackward0>)


In [17]:
# backward pass using static input/features
import torch


x = torch.tensor(4.0, requires_grad=True)


y = x ** 2

print("y =", y)


y.backward()


print("dy/dx =", x.grad)

y = tensor(16., grad_fn=<PowBackward0>)
dy/dx = tensor(8.)


In [19]:
# Backward pass using dynamic features
import torch
f1 = float(input("Enter Feature 1: "))
f2= float(input("Enter Feature 1: "))
x=torch.tensor([f1,f2],requires_grad=True, dtype=torch.float32)
y = x[0]**3 + x[1]
print("y= ",y)
y.backward()
print("dy/dx =", x.grad)

Enter Feature 1:  45.7
Enter Feature 1:  34.8


y=  tensor(95478.7891, grad_fn=<AddBackward0>)
dy/dx = tensor([6.2655e+03, 1.0000e+00])
